services:
  echome-db:
    container_name: echome-db
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: echome_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/migrations/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  echome-backend:
    container_name: echome-backend
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - echome-db
    environment:
      - DB_HOST=echome-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=echome_db
    command: sh -c "until pg_isready -h echome-db -p 5432; do echo waiting for database; sleep 2; done && npm run dev"

volumes:
  postgres_data:
